In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 1.7307833
200 0.5715119
400 0.5074139
600 0.4718242
800 0.44758478
1000 0.42857108
1200 0.41232458
1400 0.39775506
1600 0.38433787
1800 0.37180114
2000 0.35999325
2200 0.34882212
2400 0.3382263
2600 0.32816055
2800 0.31858906
3000 0.30948088
3200 0.30080855
3400 0.29254702
3600 0.28467283
3800 0.27716395
4000 0.2699997
4200 0.2631606
4400 0.25662813
4600 0.25038514
4800 0.24441506
5000 0.2387027
5200 0.23323365
5400 0.22799426
5600 0.22297192
5800 0.21815474
6000 0.21353151
6200 0.20909168
6400 0.20482552
6600 0.20072371
6800 0.1967777
7000 0.19297926
7200 0.18932092
7400 0.1857955
7600 0.18239635
7800 0.17911713
8000 0.17595182
8200 0.17289506
8400 0.16994148
8600 0.16708624
8800 0.16432475
9000 0.16165252
9200 0.15906553
9400 0.1565599
9600 0.15413196
9800 0.15177831
10000 0.14949562

Hypothesis:  [[0.03074029]
 [0.15884677]
 [0.30486736]
 [0.78138196]
 [0.93957496]
 [0.9801688 ]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


In [3]:
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(-tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

(759, 8) (759, 1)
0 0.97422194
200 0.73380584
400 0.68054277
600 0.65738314
800 0.6405061
1000 0.62598956
1200 0.61303777
1400 0.6013964
1600 0.59091467
1800 0.58146954
2000 0.57295144
2200 0.56526166
2400 0.5583115
2600 0.5520215
2800 0.5463204
3000 0.54114515
3200 0.53643954
3400 0.5321536
3600 0.52824324
3800 0.5246693
4000 0.52139693
4200 0.51839536
4400 0.5156375
4600 0.51309913
4800 0.5107587
5000 0.50859725
5200 0.50659776
5400 0.5047452
5600 0.5030261
5800 0.5014283
6000 0.4999411
6200 0.498555
6400 0.49726117
6600 0.49605182
6800 0.49492007
7000 0.49385962
7200 0.49286455
7400 0.4919301
7600 0.49105117
7800 0.49022377
8000 0.4894441
8200 0.48870838
8400 0.48801363
8600 0.48735696
8800 0.4867357
9000 0.48614722
9200 0.48558944
9400 0.4850604
9600 0.48455814
9800 0.4840809
10000 0.48362702

Hypothesis:  [[0.3700318 ]
 [0.9154805 ]
 [0.21602735]
 [0.94834936]
 [0.08354768]
 [0.7647524 ]
 [0.94660914]
 [0.6240097 ]
 [0.24575189]
 [0.53068644]
 [0.7005222 ]
 [0.17214663]
 [0.165432

In [4]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 1.1444304
200 0.5701725
400 0.46664643
600 0.3719219
800 0.28220817
1000 0.23855816
1200 0.21593893
1400 0.1971462
1600 0.18127106
1800 0.16768387
2000 0.15592827
--------------
[[7.4781636e-03 9.9251574e-01 6.1860369e-06]] [1]
--------------
[[0.8336169 0.1587082 0.0076748]] [0]
--------------
[[9.386088e-09 2.992087e-04 9.997008e-01]] [2]
--------------
[[7.4781636e-03 9.9251574e-01 6.1860374e-06]
 [8.3361691e-01 1.5870818e-01 7.6748026e-03]
 [9.3860884e-09 2.9920871e-04 9.9970078e-01]] [1 0 2]


In [5]:
import numpy as np
tf.set_random_seed(777)  # for reproducibility

# Predicting animal type based on various features
xy = np.loadtxt('data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7  # 0 ~ 6

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6
Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape", Y_one_hot)

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                 labels=tf.stop_gradient([Y_one_hot]))
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={
                                 X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(
                step, loss, acc))

    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

(101, 16) (101, 1)
one_hot Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape Tensor("Reshape:0", shape=(?, 7), dtype=float32)
Step:     0	Loss: 3.509	Acc: 25.74%
Step:   100	Loss: 0.685	Acc: 83.17%
Step:   200	Loss: 0.454	Acc: 88.12%
Step:   300	Loss: 0.342	Acc: 91.09%
Step:   400	Loss: 0.274	Acc: 93.07%
Step:   500	Loss: 0.226	Acc: 94.06%
Step:   600	Loss: 0.192	Acc: 94.06%
Step:   700	Loss: 0.165	Acc: 95.05%
Step:   800	Loss: 0.144	Acc: 96.04%
Step:   900	Loss: 0.128	Acc: 98.02%
Step:  1000	Loss: 0.115	Acc: 98.02%
Step:  1100	Loss: 0.104	Acc: 99.01%
Step:  1200	Loss: 0.095	Acc: 100.00%
Step:  1300	Loss: 0.087	Acc: 100.00%
Step:  1400	Loss: 0.081	Acc: 100.00%
Step:  1500	Loss: 0.075	Acc: 100.00%
Step:  1600	Loss: 0.071	Acc: 100.00%
Step:  1700	Loss: 0.066	Acc: 100.00%
Step:  1800	Loss: 0.062	Acc: 100.00%
Step:  1900	Loss: 0.059	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Predi